### ISSUE TITLE
Application name from the config

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-app#3]
It would be great to choose the name of the app by defining it in the config file. This will allow to have the command name for the cli related to the current application such as `zenodo db init` or `inspire db init`.

**Comment by lnielsen** [comment]
I'm not sure this will be possible without breaking changes to Invenio-Base.

The application name is defined [here](https://github.com/inveniosoftware/invenio-app/blob/master/invenio_app/factory.py#L105) which uses Invenio-Base. However, the application [is created](https://github.com/inveniosoftware/invenio-base/blob/master/invenio_base/app.py#L99) before any configuration [is loaded](https://github.com/inveniosoftware/invenio-base/blob/master/invenio_base/app.py#L107). 

The only option I see right now, is that we read from an environment variable like we do with [instance path](https://github.com/inveniosoftware/invenio-app/blob/master/invenio_app/factory.py#L44). But I'm not sure how reliably that would be.

**Comment by lnielsen** [comment]
This will be solved via the cookiecutter-invenio-instance which will install an extra console_script that works like the ``invenio`` cli.
