### ISSUE TITLE
ext: add "/ping" view for load-balancers/rolling-deployments

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-app#35]
Currently `cookiecutter-invenio-instance` is [adding a `/ping` view](https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/ec6ded4fa63e1b14c1dfd3d99a0e10b891f5cc85/%7B%7Bcookiecutter.project_shortname%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/views.py#L21-L24), which assists load balancers like HAProxy to figure out if a node is running and should be included in the load-balanced set. This is also used by container-based platforms like Kubernetes/OpenShift, to perform rolling deployments.

It would be nice to provide this view out of the box for all applications, and the most fitting candidate would probably be inside the [`InvenioApp` extension](https://github.com/inveniosoftware/invenio-app/blob/5133f8f14099efb368016c63b5917c9aec696836/invenio_app/ext.py#L36-L51).

Some notes:

- The view should be configurable, via e.g. `APP_PING_VIEW_ENABLED = True` and/or `APP_PING_VIEW = 'my_custom.views.ping'`
- Since this view is just accessed internally (i.e. from HAProxy, nginx, Kubernetes, etc), it should be accessible via plain HTTP as well. The only way to do so, is something [hacky like this](https://github.com/asclepias/asclepias-broker/blob/82dbc20e42e079520f33bf4e32078e3a88eac5f6/asclepias_broker/views.py#L38) or closing https://github.com/inveniosoftware/invenio-app/issues/22.

**Comment by ppanero** [comment]
Working on it

**Comment by ppanero** [comment]
The changes were merged in #36 closing this.
