### ISSUE TITLE
travis: fix build failure

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-app#63]
Python 2: https://travis-ci.org/github/inveniosoftware/invenio-app/jobs/664517380#L291

Task:
- Remove python 2 support according to the [Python 2 support RFC](https://github.com/inveniosoftware/rfcs/blob/master/framework/0016-python2.md) in order to fix build error.

**Comment by lnielsen** [comment]
A first attempt in #64, however that caused a [new build error](https://travis-ci.org/github/inveniosoftware/invenio-app/jobs/681076241) with six version conflict
